name: Portafolios

on:

  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          cp -r * /var/www/php
